import type { Metadata } from "next";
import { Inter, Noto_Sans } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { redirect } from "next/navigation";

const NotoSans = Noto_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  const session = await auth();
  console.log(session?.user.uid);
  // if (!session) {
  //   redirect('/login');
  // }
  return (
    <html lang="ja">
      <body className={NotoSans.className}>{children}</body>
    </html>
  );
}
